server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      sql-true: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
